---
title: "Model Evaluation"
output: pdf_document
author: Richa Jain and Estee Cramer
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**Introduction**

Many of the models submitting to the COVID-19 Forecast Hub incorporate data about social distancing, mobility, or non-pharmaceutical interventions (NPIs). We look to compare these models with each other and with models that do not incorporate such data and evaluate their performance.

TODO: 
1. define social distancing , NPIs , mobility 
2. 


**Methods** 

*Step 1: Create Table of Model Characteristics*

* Look for which models use social distancing data 
* Data used by models (demographic data, hospitalization data) 
* Model type (SEIR, Baysian, statistical) 
* Look for models that fit criteria but do not include social distancing data 

*Step 2: Inclusion Criteria*

* Locations: Florida, Texas, Massachusetts, New York, California, Michigan
* Time period: November 1 2020 - December 31 2020
* Target: Incident Cases 
* Horizons:
* Models: 
  * 2 models with both mobility and social distancing
    * CU-select, JHUAPL-Bucky
  * 2 models with neither mobility nor social distancing
    * COVIDhub-baseline, LANL-GrowthRate
  * 2 models with only mobility 
    * IowaStateLW-STEM, UVA-Ensemble
  * 1 model with only social distancing
    * JHU_IDD-CovidSP

*Step 3: Evaluation graphs* 

* After deciding on inclusion criteria, use covidhubUtils to score forecasts and determine which models are best. 

*Step 4: Linear regression*

* Exposure / variable : social distancing, data sources, model type

**Key Information about the Locations** 

(maybe change timelines to just 1 key date from summer 2020, winter 2020, and now)

Three of the locations that were chosen either never had a mask mandate or removed the mask mandate early in 2021 (FL, TX, MA) while the other three locations plan to remove mask mandates sometime in the summer of 2021 (NY, CA, MI). 

*Florida Timeline*

* March 9 2020: state of emergency
* April 1 2020: stay at home orders
* May 4 2020: reopening begings
* July 11 2020: Disney reopens
* November and December 2020: Multiple counties continued to extended their state of emergencies
* December 17 2020: reported 13148 new cases (largest since July 2020)
* (Never had a mask mandate)

*Texas Timeline*

* March 13 2020: state disaster declared
* March 19 2020: state mandates
* March 24 2020: stay at home orders
* May 1 2020: phase 1 reopening 
* May 18 2020: phase 2 reopening 
* June 3 2020: phase 3 reopening 
* June 26 2020: reopening paused 
* July 2 2020: mask mandate put in place
* Septemeber 17 2020: reopening starts up again 
* November 21-25 2020: new infections and cases increase
* December 2020: first month with more than 6000 fatalities
* March 2 2021: remove mask mandate
* March 10 2021: state fully reopens

*Massachusetts Timeline*

* March 13 2020: limited gatherings throughout the state
* March 15 2020: more restrictions put into place
* March 23 2020: stay at home orders
* May 6 2020: mask mandate put in place
* May 18 2020: phase 1 reopening
* June 8 2020: phase 2 reopening
* July 2 2020: phase 3 reopening 
* September 29 2020: phase 3 step 2 reopening 
* November 2 2020: statewide curfew
* December 8 2020: all cities/towns rollback to phase 3 step 1 of reopening
* May 29: state full reopens, no more mask mandate

*New York Timeline*

* March 7 2020: state of emergency declared
* April 15 2020: mask mandate put in place
* April-May 2020: stay at home orders
* May 15 2020: slight reopening
* June 8 2020: NYC phase 1 reopening
* June 22 2020: NYC phase 2 reopening 
* July 6 2020: phase 3 reopening 
* July 19 2020: phase 4 reopening 
* November 13 2020: new restrictions 
* December 1 2020: slight reopening of schools 
* December 11 2020: slight reopening of gyms and salons
* December 23 2020: full reopening of gyms 
* February 15 2021: NYC middle schools go back to in person 
* March 22 2021: NYC high schools go back to in person

*California Timeline*

* March 4 2020: state of emergency declared
* March 12 2020: cancel large events
* March 19 2020: stay at home orders
* May 8 2020: beginning of phase 2 reopening 
* May 26 2020: phase 3 reopening 
* June 18 2020: mask mandate put in place
* July 13 2020: 30 counties ordered to close indoor businesses
* July 22 2020: CA surpasses NY for confirmed cases
* October 10 2020: loosen restrictions on private outdoor gatherings
* November 19 2020: statewide curfew
* December 3 2020: new stay at home oder
* January 25 2021: no counties have stay at home order

*Michigan Timeline*

* February 28 2020: state will activate emergency operations center
* March 10 2020: state of emergency declared
* March 13 2020: close schools and place restrictions on gatherings
* March 16 2020: close public places
* March 23 2020: stay at home orders
* April 9 2020: extend stay at home orders through all of April 
* May 1 2020: extend state of emergency 
* May 22 2020: extend stay at home orders until June 12 and state of emergency until June 19
* October 5 2020: mask mandate put in place
* October 9 2020: public places reopen
* November 2020: rapid increase in cases
* December 7 2020: statewide partial shutdown 
* December 18 2020: some indoor spaces reopen 
* March 5 2021: loosen restrictions 
* May 4 2021: state relaxes restrictions on masks 
* June 1 2021: crowd size restrictions for outdoor events lifted
* July 1 2021: all mandates lifted



**Key Information about the Models that were chosen**

Model | Case Data | Model Type | Social Distancing Assumptions? | Mobility Data? | Notes
------------- | ------------- | ------------- | ------------- | ------------- | -------------
CU-select | Johns Hopkins, USAFacts | SEIR model | yes | yes | NPI Scenarios
JHUAPL-Bucky | JHU CSSE, CDC | Spatial compartment model | yes | yes | accounts for NPIs
COVIDhub-baseline | JHU CSSE | Median prediction at all future horizons | no | no | 
LANL-GrowthRate | JHU CSSE | Statistical dynamical growth model | no | no |
IowaStateLW-STEM | NYT, Johns Hopkins, Covid Tracking Project, USA Facts | Nonparametric space-time disease transmission model | no | yes | 
UVA-Ensemble | CDC | AR, ISTM, SEIR model | no | yes (Baidu) | 
JHU_IDD-CovidSP | Johns Hopkins | State-level metapopulation model with commuting and stochastic SEIR disease dynamics with social-distancing indicators | yes | no |

**Results**

Relative WIS: Location & Date | CU-select | JHUAPL-Bucky | COVIDhub-baseline | LANL-GrowthRate | IowaStateLW-Stem | UVA-Ensemble | JHU_IDD-CovidSP 
-------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- 
California, December 25 2020 | 1.206475 | 1.522587	 | 1.164057	| 1.488985 | 1.113371 | 	1.628289	|	1.069115	
California, December 3 2020 | 5.370204 | 1.808852	| 6.449432 | 2.792104	|	4.390412	|	3.733466	|	4.152183	
Florida, December 25 2020 | 0.6055555 | 0.2638828 | 0.4991921 | 0.9095747 | 0.4722359 | 1.3920509 | 0.6998647 
Florida, November 26-December 25 2020 | 0.7842814	| 0.2292115	| 0.6720338 | 0.4723293 | 0.5732159 | 1.6918945 | 0.7714050	
Massachusetts, December 25 2020 | 1.3995285	|	1.0997744	|	0.4726977	|	1.4435453	|	0.7757552	|	1.1065041	|	0.8408508	
Massachusetts, November 2 2020 | 3.979697	|	2.661800 | 4.719158 | 2.044704 |	2.500814 | NA | 3.030182	
Massachusetts, December 8 2020 | 2.582925	| 1.141068 | 1.590219 |	1.459193 | 1.453894 | 1.378589 | 1.588102		
Michigan, December 25 2020 | 1.2861948 | 0.5557569 | 1.4603111 | 0.5654227 | 1.5507782 | 0.7877323 | 0.8708405	
Michigan, November 8 2020 | 1.680514 | 1.540251 | 1.631705 | 1.134571 | 1.864215 | NA | 1.664119	
New York, December 25 2020 | 0.6282631 | 1.3932701 | 0.5790893 | 0.7732911 | 0.5692396 | 1.0451479 | 1.1616783	
New York, November 12 2020 | 5.958968 | 4.937624 | 5.834913 | 2.874151 | 3.025552 | NA | 3.605014	
Texas, December 25 2020 |	1.9554059	|	1.7943020	|	0.4314701	|	0.9648386	|	0.8648496	|	1.4402983	|	0.3218461	
Texas, November 26-December 25 2020 |	2.1685951	|	2.1040233	|	0.4558419	|	0.4036692	|	0.7097249| 2.3080121 | 0.2761288	
Texas, November 21-November 25 2020 |	1.3140754	|	1.5145767	|	0.8605251 |	0.3951242	|	0.6952534	|	1.8039064	|	0.5469355	

*Summary of Models*
*Model Accuracy*
*Model Accuracy by Group*

**Discussion**




#mob: 
#UMich-RidgeTfReg 

**Model Chart 2**
\newpage

Model | Case Data | Model Type | Social Distancing Assumptions? | Mobility Data? | Notes
------------- | ------------- | ------------- | ------------- | ------------- | -------------
COVIDhub-baseline | JHU CSSE | Median prediction at all future horizons | no | no | 
LANL-GrowthRate | JHU CSSE | Statistical dynamical growth model | no | no |
COVIDhub-ensemble | | Unweighted average or median of submitted forecasts | no | no
RobertWalraven-ESG | JHU CSSE | SEIR model | no | no
IowaStateLW-STEM | NYT, Johns Hopkins, Covid Tracking Project, USA Facts | Nonparametric space-time disease transmission model | no | yes | 
UVA-Ensemble | CDC | AR, ISTM, SEIR model | no | yes (Baidu) | 
JHU_CSSE-DECOM | JHU CSSE | Empirical machine learning model | no | yes (SafeGraph) | 
UMich-RidgeTfReg | JHU CSSE | Ridge regression | no | yes




